#ifndef _ANIMS_H_
#define _ANIMS_H_

#define ANIM_SIG(x) void x##_setup(); void x##_drawFrame();
#define ANIM_DRAW(name) case ANIM_##name: name##_drawFrame(); break;
#define ANIM_BEGIN(name)  case ANIM_##name: name##_setup(); name##_drawFrame(); break;



#define ANIMATION_ENUM \
    enum animName_t {\
        ANIM_NONE = 0\
        \
        , ANIM_RED_BLUE \
        , ANIM_FRONT_BACK_LINE \
        , ANIM_RAINBOW \
        , ANIM_REDS \
        , ANIM_RANDO \
        , ANIM_KITT \
        , ANIM_RAINBOW_SINGLE \
        , ANIM_SPARKLE \
        \
        , ANIM_LAST\
        \
    };
        // , ANIM_JORDAN_RUNWAY\
        // , ANIM_JPERF_START\
        // \
        // , ANIM_JPERF_FBLOBS\
        // , ANIM_JPERF_FSPARKLE\
        // , ANIM_JPERF_FPULSES\
        // , ANIM_JPERF_FSPOTS\
        // , ANIM_JPERF_BREATH\
        // \
        // , ANIM_JPERF_MBOUNCE\
        // , ANIM_JPERF_MSNARE\
        // , ANIM_JPERF_OFF\
        // , ANIM_JPERF_MSPARKLE\
        // , ANIM_JPERF_MCLAP\
        // , ANIM_JPERF_MBOUNCE_END\
        // \
        // , ANIM_JPERF_END\

        // , ANIM_ROBOT_HEAD_SHRUGS \
        // , ANIM_ROBOT_HEART_BEAT \
        // , ANIM_ROBOT_SLEEP \
        // , ANIM_ROBOT_ONE_EYE_WAKE \
        // , ANIM_ROBOT_RAINBOW_WAKE_FILL \
        // , ANIM_ROBOT_RAINBOW_WAKE_ROT \
        // \
        // , ANIM_ROBOTX \
        // , ANIM_FLOOD\
        // , ANIM_SPARKLE\
        // , ANIM_RAINBOW\
        // , ANIM_BRIGHT_FO\
        // , ANIM_RANDO_FADE\
        // , ANIM_WHITE\
        // , ANIM_HALF_WHITE\
        // \
    

#define ANIMATION_SIGNATURES \
    ANIM_SIG(RED_BLUE) \
    ANIM_SIG(FRONT_BACK_LINE) \
    ANIM_SIG(SPARKLE) \
    ANIM_SIG(RANDO) \
    ANIM_SIG(RAINBOW) \
    ANIM_SIG(RAINBOW_SINGLE) \
    ANIM_SIG(KITT) \
    ANIM_SIG(REDS) \

    // ANIM_SIG(FLOOD) \
    // ANIM_SIG(RAINBOW) \
    // ANIM_SIG(BRIGHT_FO) \
    // ANIM_SIG(RANDO_FADE) \
    // ANIM_SIG(SPARKLE) \
    // ANIM_SIG(WHITE) \
    // ANIM_SIG(HALF_WHITE) \
    // \
    // ANIM_SIG(ROBOTX) \
    // ANIM_SIG(ROBOT_HEAD_SHRUGS) \
    // ANIM_SIG(ROBOT_HEART_BEAT) \
    // ANIM_SIG(ROBOT_SLEEP) \
    // ANIM_SIG(ROBOT_ONE_EYE_WAKE) \
    // ANIM_SIG(ROBOT_RAINBOW_WAKE_FILL) \
    // ANIM_SIG(ROBOT_RAINBOW_WAKE_ROT) \

    // ANIM_SIG(JORDAN_RUNWAY) \
    // ANIM_SIG(JPERF_START) \
    // ANIM_SIG(JPERF_FBLOBS) \ 
    // ANIM_SIG(JPERF_FSPARKLE) \ 
    // ANIM_SIG(JPERF_FPULSES) \ 
    // ANIM_SIG(JPERF_FSPOTS) \ 
    // ANIM_SIG(JPERF_BREATH) \ 
    // ANIM_SIG(JPERF_MBOUNCE) \ 
    // ANIM_SIG(JPERF_MSNARE) \ 
    // ANIM_SIG(JPERF_OFF) \ 
    // ANIM_SIG(JPERF_MSPARKLE) \ 
    // ANIM_SIG(JPERF_MCLAP) \ 
    // ANIM_SIG(JPERF_MBOUNCE_END) \ 
    // ANIM_SIG(JPERF_END) \ 
 

    
#define ANIMATION_DRAWS \
    ANIM_DRAW(RED_BLUE) \
    ANIM_DRAW(FRONT_BACK_LINE) \
    ANIM_DRAW(SPARKLE) \
    ANIM_DRAW(RANDO) \
    ANIM_DRAW(RAINBOW) \
    ANIM_DRAW(RAINBOW_SINGLE) \
    ANIM_DRAW(KITT) \
    ANIM_DRAW(REDS) \

    // ANIM_DRAW(FLOOD) \
    // ANIM_DRAW(RAINBOW) \
    // ANIM_DRAW(BRIGHT_FO) \
    // ANIM_DRAW(RANDO_FADE) \
    // ANIM_DRAW(SPARKLE) \
    // ANIM_DRAW(WHITE) \
    // ANIM_DRAW(HALF_WHITE) \
    // \
    // ANIM_DRAW(ROBOTX) \
    // ANIM_DRAW(ROBOT_HEAD_SHRUGS) \
    // ANIM_DRAW(ROBOT_HEART_BEAT) \
    // ANIM_DRAW(ROBOT_SLEEP) \
    // ANIM_DRAW(ROBOT_ONE_EYE_WAKE) \
    // ANIM_DRAW(ROBOT_RAINBOW_WAKE_FILL) \
    // ANIM_DRAW(ROBOT_RAINBOW_WAKE_ROT) \

    // ANIM_DRAW(JORDAN_RUNWAY) \
    // ANIM_DRAW(JPERF_START) \ 
    // ANIM_DRAW(JPERF_FBLOBS) \ 
    // ANIM_DRAW(JPERF_FSPARKLE) \ 
    // ANIM_DRAW(JPERF_FPULSES) \ 
    // ANIM_DRAW(JPERF_FSPOTS) \ 
    // ANIM_DRAW(JPERF_BREATH) \ 
    // ANIM_DRAW(JPERF_MBOUNCE) \ 
    // ANIM_DRAW(JPERF_MSNARE) \ 
    // ANIM_DRAW(JPERF_OFF) \ 
    // ANIM_DRAW(JPERF_MSPARKLE) \ 
    // ANIM_DRAW(JPERF_MCLAP) \ 
    // ANIM_DRAW(JPERF_MBOUNCE_END) \ 
    // ANIM_DRAW(JPERF_END) \ 


#define ANIMATIONS_BEGIN \
    ANIM_BEGIN(RED_BLUE) \
    ANIM_BEGIN(FRONT_BACK_LINE) \
    ANIM_BEGIN(SPARKLE) \
    ANIM_BEGIN(RANDO) \
    ANIM_BEGIN(RAINBOW) \
    ANIM_BEGIN(RAINBOW_SINGLE) \
    ANIM_BEGIN(KITT) \
    ANIM_BEGIN(REDS) \

    // ANIM_BEGIN(FLOOD) \
    // ANIM_BEGIN(RAINBOW) \
    // ANIM_BEGIN(BRIGHT_FO) \
    // ANIM_BEGIN(RANDO_FADE) \
    // ANIM_BEGIN(SPARKLE) \
    // ANIM_BEGIN(WHITE) \
    // ANIM_BEGIN(HALF_WHITE) \
    // \
    // ANIM_BEGIN(ROBOTX) \
    // ANIM_BEGIN(ROBOT_HEAD_SHRUGS) \
    // ANIM_BEGIN(ROBOT_HEART_BEAT) \
    // ANIM_BEGIN(ROBOT_SLEEP) \
    // ANIM_BEGIN(ROBOT_ONE_EYE_WAKE) \
    // ANIM_BEGIN(ROBOT_RAINBOW_WAKE_FILL) \
    // ANIM_BEGIN(ROBOT_RAINBOW_WAKE_ROT) \

    // ANIM_BEGIN(JORDAN_RUNWAY) \
    // ANIM_BEGIN(JPERF_START) \ 
    // ANIM_BEGIN(JPERF_FBLOBS) \ 
    // ANIM_BEGIN(JPERF_FSPARKLE) \ 
    // ANIM_BEGIN(JPERF_FPULSES) \ 
    // ANIM_BEGIN(JPERF_FSPOTS) \ 
    // ANIM_BEGIN(JPERF_BREATH) \ 
    // ANIM_BEGIN(JPERF_MBOUNCE) \ 
    // ANIM_BEGIN(JPERF_MSNARE) \ 
    // ANIM_BEGIN(JPERF_OFF) \ 
    // ANIM_BEGIN(JPERF_MSPARKLE) \ 
    // ANIM_BEGIN(JPERF_MCLAP) \ 
    // ANIM_BEGIN(JPERF_MBOUNCE_END) \ 
    // ANIM_BEGIN(JPERF_END) \ 


#endif //  _ANIMS_H_

